---
- name: dome9_lease
  debug:
    var: dome9_lease
    verbosity: 2

- name: Acquire dome9 Dynamic Lease
  uri:
    url: https://api.dome9.com/v2/accesslease/aws
    user: "{{ dome9_api_key_id }}"
    password: "{{ dome9_api_key_secret }}"
    method: POST
    body:
      region: "{{ dome9_lease.region }}"
      securityGroupId: "{{ dome9_lease.sg }}"
      ip: "{{ dome9_lease.ip | default(omit) }}"
      length: "{{ dome9_lease.length }}"
      protocol: "{{ dome9_lease.protocol }}"
      portFrom: "{{ dome9_lease.port_from | int }}"
      portTo: "{{ dome9_lease.port_to | int }}"
      note: "{{ dome9_lease.note | default(omit) }}"
    body_format: json
    HEADER_Content-Type: application/json
    force_basic_auth: yes
    return_content: yes
    status_code: 201
  register: dome9_lease_response
  when:
    - dome9_lease is defined
    - dome9_lease.action == "acquire"
    - dome9_lease.region is defined
    - dome9_lease.region != ""
    - dome9_lease.sg is defined
    - dome9_lease.sg != ""
    - dome9_lease.length is defined
    - dome9_lease.length != ""
    - dome9_lease.protocol is defined
    - dome9_lease.protocol != ""
    - dome9_lease.port_from is defined
    - dome9_lease.port_from != ""

- name: dome9_lease_response
  debug:
    var: dome9_lease_response
    verbosity: 2

- name: Add lease_id to dome9_lease
  set_fact:
    dome9_lease.id: 0