---
- name: Acquire dome9 Dynamic Lease (deprecated)
  uri:
    url: https://api.dome9.com/v2/accesslease/aws
    user: "{{ dome9_api_key_id }}"
    password: "{{ dome9_api_key_secret }}"
    method: POST
    body:
      region: "{{ dome9_lease.region | default(dome9_lease_defaults.region) }}"
      securityGroupId: "{{ dome9_lease.sg | int }}"
      ip: "{{ dome9_lease.ip | default(ansible_default_ipv4.address) }}"
      length: "{{ dome9_lease.length | default(dome9_lease_defaults.length) }}"
      protocol: "{{ dome9_lease.protocol | default(dome9_lease_defaults.protocol) }}"
      portFrom: "{{ dome9_lease.port_from | int }}"
      portTo: "{{ dome9_lease.port_to | int }}"
      note: "{{ dome9_lease.note | default(omit) }}"
    body_format: json
    force_basic_auth: yes
    return_content: yes
    status_code: 201
  register: dome9_lease_response
  when:
    - dome9_lease_version is not defined
    - dome9_lease is defined
    - dome9_lease.action == "acquire"
    - dome9_lease.sg is defined
    - dome9_lease.sg is not none
    - dome9_lease.sg != ""
    - dome9_lease.port_from is defined
    - dome9_lease.port_from is not none
    - dome9_lease.port_from != ""

- name: Acquire dome9 Dynamic Lease
  uri:
    url: https://api.dome9.com/v2/accesslease/aws
    user: "{{ dome9_api_key_id }}"
    password: "{{ dome9_api_key_secret }}"
    method: POST
    body:
      region: "{{ dome9_lease_region }}"
      securityGroupId: "{{ dome9_lease_sg | int }}"
      ip: "{{ dome9_lease_ip }}"
      length: "{{ dome9_lease_length }}"
      protocol: "{{ dome9_lease_protocol  }}"
      portFrom: "{{ dome9_lease_port_from | int }}"
      portTo: "{{ dome9_lease_port_to | int }}"
      note: "{{ dome9_lease_note | default(omit) }}"
    body_format: json
    force_basic_auth: yes
    return_content: yes
    status_code: 201
  register: dome9_lease_response
  when:
    - dome9_lease_version is defined
    - dome9_lease_version == "2017.05.08"
    - dome9_lease_action == "acquire"
    - dome9_lease_sg is defined
    - dome9_lease_sg is not none
    - dome9_lease_sg != ""
    - dome9_lease_port_from is defined
    - dome9_lease_port_from is not none
    - dome9_lease_port_from != ""

- name: dome9_lease_response
  debug:
    var: dome9_lease_response
    verbosity: 2
  when:
    - dome9_lease_response is defined

- name: Set dome9_lease_id
  set_fact:
    dome9_lease_id: "{{ dome9_lease_response.json.id }}"
  when:
    - dome9_lease_response is defined
    - dome9_lease_response.skipped is undefined
    - dome9_lease_response.json is defined
    - dome9_lease_response.json.id is defined

- name: Terminate dome9 Dynamic Lease (deprecated)
  uri:
    url: "https://api.dome9.com/v2/accesslease/{{ dome9_lease_id }}"
    user: "{{ dome9_api_key_id }}"
    password: "{{ dome9_api_key_secret }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 204
  when:
    - dome9_lease is defined
    - dome9_lease.action == "terminate"
    - dome9_lease_id is defined
    - dome9_lease_id is not none
    - dome9_lease_id != ""

- name: Terminate dome9 Dynamic Lease
  uri:
    url: "https://api.dome9.com/v2/accesslease/{{ dome9_lease_id }}"
    user: "{{ dome9_api_key_id }}"
    password: "{{ dome9_api_key_secret }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 204
  when:
    - dome9_lease_version is defined
    - dome9_lease_version == "2017.05.08"
    - dome9_lease_action is defined
    - dome9_lease_action == "terminate"
    - dome9_lease_id is defined
    - dome9_lease_id is not none
    - dome9_lease_id != ""